#!/bin/bash

# Check if running as root
if [ "$(id -u)" -ne 0 ]; then
    echo "Please run this script as root"
    exit 1
fi

# Set the IP addresses to be configured
localhost_ip="127.0.0.2"
facebook_ip="8.8.8.8"

# Update /etc/hosts file
sed -i "s/^127.0.0.1[[:space:]]\+localhost/127.0.0.1 localhost\n${localhost_ip} localhost/" /etc/hosts
sed -i "s/^.*facebook.com[[:space:]]\+.*$/127.0.0.1 facebook.com\n${facebook_ip} facebook.com/" /etc/hosts

# Output success message
echo "Successfully configured IP addresses:"
echo "localhost resolves to ${localhost_ip}"
echo "facebook.com resolves to ${facebook_ip}"

