#!/bin/bash

# Get active IPv4 IPs using ifconfig
ipv4_ips=$(ifconfig | grep -oE "inet (addr:)?([0-9]*\.){3}[0-9]*" | awk '{print $2}' | grep -v '127.0.0.1')

# Display the active IPv4 IPs
echo "$ipv4_ips"

